comet_api_key: 'typxJnomsSO2rgJMpODsabyCp'
comet_workspace: 'sanjana-226'
default_val_root: 'new-splits2/val'
default_train_root: 'new-splits2/train-splits'
default_test_root: 'new-splits2/test'
project_name: frnas
checkpoints_root: checkpoints/
metadata_file: celeba/timm_model_metadata.csv
demographics_file: celeba/CelebA_demographics.txt
